spring:
  profiles:
    active: ${APP_ENV}
  application:
    name: future-gateway
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080
zuul:
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 120000

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000

---

spring:
  profiles: development

zuul:
  sensitiveHeaders:
  routes:
    authorization-server:
      path: /authserv/**
      url: http://localhost:8084
    payment-service:
      path: /paymentserv/**
      url: http://localhost:8088
    wallet-service:
      path: /walletserv/**
      url: http://localhost:8086

---


spring:
  profiles: production

zuul:
  sensitiveHeaders:
  routes:
    authorization-server:
      path: /authserv/**
      url: http://future-auth-server
    wallet-service:
      path: /walletserv/**
      url: http://future-wallet-service
    payment-service:
      path: /paymentserv/**
      url: http://future-payment-service